runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

# [START configuration]
endpoints_api_service:
  # The following values are to be replaced by information from the output of
  # 'gcloud endpoints services deploy openapi-appengine.yaml' command.
  name: "sample-project-196107.appspot.com"
  config_id: "2018-03-20r1"
 # [END configuration]

#[START env]
env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
      postgresql+psycopg2://postgres:punitjain@/csuf?host=/cloudsql/sample-project-196107:us-east1:csufchatbot
#[END env]

#[START cloudsql_settings]
# Replace project and instance with the values obtained  when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: sample-project-196107:us-east1:csufchatbot
#[END cloudsql_settings]

handlers:
  - url: /docs
    static_files: docs/index.html
    upload: docs/index.html
  - url: /docs/(.*)
    static_files: docs/\1
    upload: docs/.
  - url: /api-docs
    static_files: openapi.yaml
    upload: openapi.yaml
